### ISSUE TITLE
修改meta-data

### ISSUE THREAD

**Issue by 503380393** [CodyGit/ManifestEditor#1]
我尝试修改meta-data，但抛出错误
if attr_dict["type"] == TypedValue.TYPE_STRING:
TypeError: 'NoneType' object is not subscriptable

**Comment by CodyGit** [comment]
> 我尝试修改meta-data，但抛出错误
> if attr_dict["type"] == TypedValue.TYPE_STRING:
> TypeError: 'NoneType' object is not subscriptable

可以把你的代码贴一下么？ 想看看你是怎么调用的

**Comment by CodyGit** [comment]
@503380393  我查了一下报错，应该是调用上传参的问题，这里不要加"android:

```python
    old_attr_obj = {
        "tag":"meta-data",
    }
    new_attr_obj = [
        {"key": "name", "value": "com.xxx1"}  # 注意这里不要加 "android:"
    ]
    modify_xml_attr(input_xml, old_attr_obj, new_attr_obj, output_xml)
```
你看看能否解决你的问题，如果还有问题我们再沟通。

**Comment by 503380393** [comment]
> @ 503380393 我查了一下报错，应该是调用上传参的问题，这里不要加“ android：
> 
> ```python
>     old_attr_obj  = {
>          “ tag”：“元数据”，
>     }
>     new_attr_obj  = [
>         { “ key”：“ name”，“ value”：“ com.xxx1” }   ＃注意这里不要加“ android：”
>     ]
>     Modify_xml_attr（input_xml，old_attr_obj，new_attr_obj，output_xml）
> ```
> 
> 你看看能否解决你的问题，如果还有问题我们再沟通。

谢谢，已解决。很好的一个开源工具，支持，点赞

**Comment by 503380393** [comment]
这里还发现一个问题，比如修改meta-data，如果修改的值为整数的话，数字前面会有”\ “符号；
例如：
<meta-data android:name="channel" android:name="huawei"/>
修改为
<meta-data android:name="channel" android:name="\ 4399"/>
请问这种尝试过修改吗

**Comment by 503380393** [comment]
![image](https://user-images.githubusercontent.com/18692277/90708726-1400ef00-e2cd-11ea-8564-00953a1ed1e7.png)

**Comment by CodyGit** [comment]
> 这里还发现一个问题，比如修改meta-data，如果修改的值为整数的话，数字前面会有”\ “符号；
> 例如：
> 
> 修改为
> 
> 请问这种尝试过修改吗

![image](https://user-images.githubusercontent.com/2959041/90712882-9215c380-e2d6-11ea-9669-28005d5a3385.png)

我这里这里尝试了一下是正常的，方便的话可以发一份AndroidManifest.xml给我我看看

**Comment by 503380393** [comment]
> > 这里还发现一个问题，比如修改meta-data，如果修改的值为整数的话，数字前面会有”\ “符号；
> > 例如：
> > 修改为
> > 请问这种尝试过修改吗
> 
> ![image](https://user-images.githubusercontent.com/2959041/90712882-9215c380-e2d6-11ea-9669-28005d5a3385.png)
> 
> 我这里这里尝试了一下是正常的，方便的话可以发一份AndroidManifest.xml给我我看看

现在尝试又正常了，尴尬。大佬是否可以加个联系方式，后续关于apk的问题持续交流

**Comment by CodyGit** [comment]
> > > 这里还发现一个问题，比如修改meta-data，如果修改的值为整数的话，数字前面会有”\ “符号；
> > > 例如：
> > > 修改为
> > > 请问这种尝试过修改吗
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/2959041/90712882-9215c380-e2d6-11ea-9669-28005d5a3385.png)
> > 我这里这里尝试了一下是正常的，方便的话可以发一份AndroidManifest.xml给我我看看
> 
> 现在尝试又正常了，尴尬。大佬是否可以加个联系方式，后续关于apk的问题持续交流

QQ: 641914761  不算大佬，一起学习
