### ISSUE TITLE
签名问题

### ISSUE THREAD

**Issue by Harlber** [CodyGit/ManifestEditor#2]
看了下项目的逻辑，有个疑问，修改完后续重新打包的逻辑是怎么样的

**Comment by CodyGit** [comment]
> 看了下项目的逻辑，有个疑问，修改完后续重新打包的逻辑是怎么样的

只需要重新签名就可以了。

**Comment by Harlber** [comment]
了解了，感谢，我看到这个项目是有个文章讲可以不解压apk操作，我在代码中搜索了很久也没看到重新打包的代码，所以感到比较奇怪

**Comment by CodyGit** [comment]
> 了解了，感谢，我看到这个项目是有个文章讲可以不解压apk操作，我在代码中搜索了很久也没看到重新打包的代码，所以感到比较奇怪

不好意思最近在忙项目的事情，没怎么登录github，直接修改apk这块还存在问题，我会尽快修复
